{
 "title": "Gatekeeper custom dashboard",
 "description": "Visualize data from Gatekeeper",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summaries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Constraint Templates",
   "type": "stat",
   "description": "Max different constraint templates on any pod.\nThis includes audit and controller pods.\n\nAs each controller pod syncs the number of constraint templates, the number each one have loaded can briefly change until sync finishes. This number represent how many constraint templates do have the pod that have more.",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gatekeeper_constraint_templates{status=\"active\"})"
    }
   ]
  },
  {
   "title": "Sum CT in controllers",
   "type": "bargauge",
   "description": "Current number of constraint templates for all controller pods.\n\nF.e.: 2 constraint templates x 3 controller pods = total 6",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (gatekeeper_constraint_templates{pod=~\"gatekeeper-controller-manager-.+\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Active deny constraints",
   "type": "stat",
   "description": "Max active constraints with enforcement action \"deny\" on all pods.\nThis includes audit and controller pods.\nMax implies different constraint templates in the cluster, instead of sum of the same constraint templates across different pods.",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gatekeeper_constraints{status=\"active\",enforcement_action=\"deny\"})"
    }
   ]
  },
  {
   "title": "Total auidt violations",
   "type": "bargauge",
   "description": "The number of constraint audit violations detected in the last audit cycle. \nIt doesn't include violations prevented by the admission controller. As such, most probably these belong to resources deployed before some constraint and constraint templates where in place.",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (enforcement_action) (gatekeeper_violations)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Audit \"deny\" violations in time",
   "type": "timeseries",
   "description": "Total violations for constarints with \"deny\" enforcement action detected by audit in time.\nIt doesn't include violations prevented by the admission controller. As such, most probably these belong to resources deployed before some constraint and constraint templates where in place.\n\nTo check audit violations, execute:  \nkubectl describe <constraint_name>\n\nTo see admision controller blocked violations, check the Kubernetes Audit Log, or check the Gatekeeper controller pods logs (this feature has to be enabled).",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "gatekeeper_violations{enforcement_action=\"deny\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  { "title": "Audit process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Total aduit violations",
   "type": "bargauge",
   "description": "The number of constraint audit violations detected in the last audit cycle. \nIt doesn't include violations prevented by the admission controller. As such, most probably these belong to resources deployed before some constraint and constraint templates where in place.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (enforcement_action) (gatekeeper_violations)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Audit duration",
   "type": "stat",
   "description": "Latency of audit operation",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gatekeeper_audit_duration_seconds_count[10m])"
    }
   ]
  },
  {
   "title": "Audit last run time",
   "type": "stat",
   "description": "Description: Timestamp of last audit run time",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - gatekeeper_audit_last_run_time"
    }
   ]
  },
  {
   "title": "Total GroupVersionKinds",
   "type": "stat",
   "description": "Total number of watched GroupVersionKinds",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gatekeeper_watch_manager_watched_gvk{pod=~\"gatekeeper-controller.+\"}) / sum(gatekeeper_watch_manager_watched_gvk{pod=~\"gatekeeper-controller.+\"})"
    }
   ]
  },
  {
   "title": "Total GroupVersionKinds registered",
   "type": "stat",
   "description": "Total number of GroupVersionKinds with a registered watch intent",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gatekeeper_watch_manager_intended_watch_gvk{pod=~\"gatekeeper-controller.+\"}) / sum(gatekeeper_watch_manager_intended_watch_gvk{pod=~\"gatekeeper-controller.+\"})"
    }
   ]
  },
  {
   "title": "Audit \"deny\" violations in time",
   "type": "timeseries",
   "description": "Total violations for constarints with \"deny\" enforcement action detected by audit in time.\nIt doesn't include violations prevented by the admission controller. As such, most probably these belong to resources deployed before some constraint and constraint templates where in place.\n\nTo check audit violations, execute:  \nkubectl describe <constraint_name>\n\nTo see admision controller blocked violations, check the Kubernetes Audit Log, or check the Gatekeeper controller pods logs (this feature has to be enabled).",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "gatekeeper_violations{enforcement_action=\"deny\"}",
     "legendFormat": "{{admission_status}}"
    }
   ]
  },
  {
   "title": "Audit deny violations change rate",
   "type": "timeseries",
   "description": "Rate at wich the numbe of violations for constraints with \"deny\" enforcement action appear.\nMust be flat when it doesn't change, and a spike when it increases.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "irate(gatekeeper_violations{enforcement_action=\"deny\"}[5m])",
     "legendFormat": "{{admission_status}}"
    }
   ]
  },
  { "title": "Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Sum CT in controllers",
   "type": "stat",
   "description": "Current number of constraint templates for all controller pods.\n\nF.e.: 2 constraint templates x 3 controller pods = total 6",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (gatekeeper_constraint_templates{pod=~\"gatekeeper-controller-manager-.+\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Sum Constraints",
   "type": "bargauge",
   "description": "Current number of constraints\nUnderstanding this metric: Gatekeeper subscribes to a watch on all constraint resources. Whenever one is created or deleted on the cluster, this count gets updated.",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (enforcement_action) (gatekeeper_constraints)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Constraint template ingestion duration",
   "type": "histogram",
   "description": "Constraint Template ingestion duration distribution histogram\n\nWhen Gatekeeper is notified of a new constraint template, records the time from when it has loaded the resource from etcd to after OPA successfully returns from compiling the code. If there is a compilation error, the metric is not updated.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(gatekeeper_constraint_template_ingestion_count[10m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Constraints",
   "type": "timeseries",
   "description": "Number of constrains loaded per pod (audit and controller).\n\nAll pods should have the same number of constraints loaded, but when they are modified, they may take some time to be on sync.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "gatekeeper_constraints{enforcement_action=\"deny\", status=\"active\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Constraint templates",
   "type": "timeseries",
   "description": "Number of constrain templates loaded per pod (audit and controller).\n\nAll pods should have the same number of constraint templatess loaded, but when they are modified, they may take some time to be on sync.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "gatekeeper_constraint_templates{status=\"active\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Constraints change rate",
   "type": "timeseries",
   "description": "If the number of constraints in audit and controller pods do not change, this graph is a line of zero value.\n\nWhen they increase or decrease, even for a short time, you will see a spike in this graph.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "irate(gatekeeper_constraints{enforcement_action=\"deny\", status=\"active\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Constraint templates change rate",
   "type": "timeseries",
   "description": "If the number of constraint templates in audit and controller pods do not change, this graph is a line of zero value.\n\nWhen they increase or decrease, even for a short time, you will see a spike in this graph.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "irate(gatekeeper_constraint_templates{status=\"active\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Admission webook", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Mutation request count rate",
   "type": "timeseries",
   "description": "Rate of change for number of requests that are routed to all Gatekeeper admission controller mutation webhook pods.\n\nThis includes all Kubernetes operations received for processing, no matter if they were \"mutated\" or not, or if you have deployed or not mutation policies.\n\nTo see admision controller blocked violations, check the Kubernetes Audit Log, or check the Gatekeeper controller pods logs (this feature has to be enabled).\n\nTo check audit violations, execute:  \nkubectl describe <constraint_name>",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by (mutation_status, pod) (rate(gatekeeper_mutation_request_count[20m]))",
     "legendFormat": "{{mutation_status}}"
    }
   ]
  },
  {
   "title": "Validation request count rate",
   "type": "timeseries",
   "description": "Rate of change for number of requests that are routed to all Gatekeeper admission controller validation webhook pods.\n\nThis includes all Kubernetes operations received for processing, no matter if they were allowed or denied by the AC, or if you have deployed or not constraint or constraint templates.\n\nTo see admision controller blocked violations, check the Kubernetes Audit Log, or check the Gatekeeper controller pods logs (this feature has to be enabled).\n\nTo check audit violations, execute:  \nkubectl describe <constraint_name>",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum by (mutation_status, pod) (rate(gatekeeper_validation_request_count[20m]))",
     "legendFormat": "{{mutation_status}}"
    }
   ]
  },
  {
   "title": "Constraints and constraint tempaltes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 }
  },
  {
   "title": "Active deny C",
   "type": "stat",
   "description": "Max active constraints with enforcement action \"deny\" on all pods.\nThis includes audit and controller pods.\nMax implies different constraint templates in the cluster, instead of sum of the same constraint templates across different pods.",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gatekeeper_constraints{status=\"active\",enforcement_action=\"deny\"})"
    }
   ]
  },
  {
   "title": "Sum CT in controllers",
   "type": "bargauge",
   "description": "Current number of constraint templates for all controller pods.\n\nF.e.: 2 constraint templates x 3 controller pods = total 6",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (gatekeeper_constraint_templates{pod=~\"gatekeeper-controller-manager-.+\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Constraint Templates",
   "type": "stat",
   "description": "Max different constraint templates on any pod.\nThis includes audit and controller pods.\n\nAs each controller pod syncs the number of constraint templates, the number each one have loaded can briefly change until sync finishes. This number represent how many constraint templates do have the pod that have more.",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gatekeeper_constraint_templates{status=\"active\"})"
    }
   ]
  },
  {
   "title": "Active dryrun C",
   "type": "stat",
   "description": "Max active constraints with enforcement action \"dryrun\" on all pods.\nThis includes audit and controller pods.\nMax implies different constraint templates in the cluster, instead of sum of the same constraint templates across different pods.",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gatekeeper_constraints{status=\"active\",enforcement_action=\"dryrun\"})"
    }
   ]
  },
  {
   "title": "Error C",
   "type": "stat",
   "description": "Max constraints with status \"error\" on all pods.\nThis includes audit and controller pods.\nMax implies different constraint templates in the cluster, instead of sum of the same constraint templates across different pods.",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gatekeeper_constraint_templates{status=\"error\"})"
    }
   ]
  },
  {
   "title": "Sum Constraints",
   "type": "bargauge",
   "description": "Current number of constraints\nUnderstanding this metric: Gatekeeper subscribes to a watch on all constraint resources. Whenever one is created or deleted on the cluster, this count gets updated.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (enforcement_action) (gatekeeper_constraints)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Active warn C",
   "type": "stat",
   "description": "Max active constraint with enforcement action \"warn\" on all pods.\nThis includes audit and controller pods.\nMax implies different constraint templates in the cluster, instead of sum of the same constraint templates across different pods.",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gatekeeper_constraints{status=\"active\",enforcement_action=\"warn\"})"
    }
   ]
  },
  {
   "title": "Active unrecognized C",
   "type": "stat",
   "description": "Max active constraints with enforcement action \"unrecognized\" on all pods.\nThis includes audit and controller pods.\nMax implies different constraint templates in the cluster, instead of sum of the same constraint templates across different pods.",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gatekeeper_constraints{status=\"active\",enforcement_action=\"unrecognized\"})"
    }
   ]
  },
  { "title": "Alerts and deployed charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Alerts firing",
   "type": "alertlist",
   "description": "All Prometheus alert rules firing",
   "gridPos": { "h": 17, "w": 9, "x": 0, "y": 54 }
  },
  {
   "title": "Helm releases",
   "type": "table",
   "gridPos": { "h": 17, "w": 15, "x": 9, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(helm_chart_info{chart=~\".*\", namespace=~\".*\", release=~\".*\"}) by (chart, release, namespace, version) != 2"
    }
   ]
  }
 ]
}